### ISSUE TITLE
Unexpected keyword argument

### ISSUE THREAD

**Issue by carlosaguilarmelchor** [tamuctf/portable-challenges-plugin#13]
First of all thanks for contributing with this plugin !
I got the following error when trying to export my challenges 

`Traceback (most recent call last):
  File "exporter.py", line 166, in <module>
    out_stream.write(export_challenges(args.out_file, args.dst_attachments, args.src_attachments, tarfile))
  File "exporter.py", line 135, in export_challenges
    return yaml.safe_dump_all(chals_list, default_flow_style=False, allow_unicode=True, explicit_start=True, sort_keys=False)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 208, in safe_dump_all
    return dump_all(documents, stream, Dumper=SafeDumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
`

I can send you the file to import the ctf if required to reproduce the error. (it is private as it is for student challenges).

**Comment by cpeter** [comment]
hi @carlosaguilarmelchor, I can have a look at the problem. Please let me know what ctfd version were you using and also please provide a sample import file. You can change the content so it would not be a problem for the students. Or just email it to me.

**Comment by cpeter** [comment]
@carlosaguilarmelchor can you do me a favour and update your PyYAML and test if again? From the error message it feels like you are using an older PyYAML

**Comment by carlosaguilarmelchor** [comment]
> hi @carlosaguilarmelchor, I can have a look at the problem. Please let me know what ctfd version were you using and also please provide a sample import file. You can change the content so it would not be a problem for the students. Or just email it to me.

I'll be glad to ! But I do not have your email :)

**Comment by carlosaguilarmelchor** [comment]
> @carlosaguilarmelchor can you do me a favour and update your PyYAML and test if again? From the error message it feels like you are using an older PyYAML

➜  programmation pip3 install PyYAML
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (3.12)
WARNING: You are using pip version 20.1.1; however, version 20.3.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
➜  programmation cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

Shall I upgrade to 20.04 ... ?

**Comment by carlosaguilarmelchor** [comment]
> @carlosaguilarmelchor can you do me a favour and update your PyYAML and test if again? From the error message it feels like you are using an older PyYAML

that did it thank you ! Maybe a minimum version check could help others ! issue closed thx
