### ISSUE TITLE
Error 404 - File not found

### ISSUE THREAD

**Issue by vincentroberge** [tamuctf/portable-challenges-plugin#17]
Hi. I installed the plugin in the plugin directory. I set the permissions to 775. From the CTFd gui, I can navigate to the /admin/transfer tab, but I get a "Error 404 File not found". Could you help me debug my installation. My CTFd installation is based on version 3.4.0 and it is working correctly. Thank you.

**Comment by cpeter** [comment]
Hi @vincentroberge ,
I can try to help. Do you have PyYML installed?

**Comment by vincentroberge** [comment]
Yes, I do have PyYAML installed. I run CTFd using gunicorn. If I restart the gunicorn service after copying the plugin files over it works. Thank you for offering your help. You can close the issue.
