### ISSUE TITLE
Exporting number of attempts for a challenge

### ISSUE THREAD

**Issue by vincentroberge** [tamuctf/portable-challenges-plugin#18]
In the current version of the plugin, the number of attempts for a challenge are not exported or imported. I think it would be a good feature to add. Do you think it would be worth it to add it? Thank you.

**Comment by cpeter** [comment]
Hi @vincentroberge , honestly that would be out of scope. The greatest benefit of the plugin is to set up a new competition quickly and easily. At this stage it’s irrelevant how many tries there have been. 
You are welcome to make a PR if you think others would benefit from this feature.

**Comment by cpeter** [comment]
After all I added support for max_attempts.

**Comment by vincentroberge** [comment]
Thank you so much. This will be very useful for me.

**Comment by cpeter** [comment]
@vincentroberge have you tried the latest checked in code? If you follow the link from crfd pluging that will point to the previous version. Make sure you check out master. Let me know.

**Comment by vincentroberge** [comment]
@cpeter It is working perfectly. Thank you so much and thank you for you patience.
