### ISSUE TITLE
Still functional?

### ISSUE THREAD

**Issue by arxenix** [tamuctf/portable-challenges-plugin#3]
Just wanted to know if this plugin is still functional on the latest CTFd. It's exactly the sort of thing we are looking for.

**Comment by ameserole** [comment]
We haven't maintained it since 1.2.0 so probably not. Feel free to fork it and add any updates as needed. CTFd also already has support for creating backups for CTFs which has pretty similar functionality https://github.com/CTFd/CTFd/wiki/Getting-Started#saving-your-ctf

**Comment by jimender2** [comment]
I can confirm that this plugin does not work for the latest version of CTFd.

**Comment by cpeter** [comment]
I made a PR that will make this plugin compatible with CTFd v2.3.2 and also added support for hints, plus a few extras :)

The built-in export will save a bunch of JSON files that are very hard to update. If the CTFd version changes occasionally importing the JSON is not working anymore. Hence I liked the YAML challenge files.

**Comment by cpeter** [comment]
Now supports Dynamic Challenges as well!
