### ISSUE TITLE
Document how to install using a custom Dockerfile

### ISSUE THREAD

**Issue by obilodeau** [tamuctf/portable-challenges-plugin#7]
This plugin can be installed with minimal disruption by leveraging upstream's `Dockerfile`.

This worked:

```
FROM ctfd/ctfd:mark-2.4.2

USER root
RUN pip install PyYAML --no-cache-dir

USER 1001
WORKDIR /opt/CTFd/CTFd/plugins/
RUN git clone --depth=1 --branch=master https://github.com/tamuctf/ctfd-portable-challenges-plugin.git && \
    rm -rf .ctfd-portable-challenges-plugin/.git/

WORKDIR /opt/CTFd
```

This is useful if you use a dockerized CTFd instance. If you are interested I can do a PR to document it. Let me know.

**Comment by cpeter** [comment]
hey @obilodeau,

Can you please do a PR?

Thx,
-Peter

**Comment by obilodeau** [comment]
My CTF101 on CTFd was today but we have a bigger CTF on another infra over the weekend. I'll do the PR later next week after some time off but I used your plugin with CTFd 2.4.2 and it worked fine importing and exporting.

**Comment by obilodeau** [comment]
Sorry I haven't delivered that documentation @cpeter. I forgot.

I recreated a new environment yesterday and used [ctfcli](https://github.com/CTFd/ctfcli). It works well enough that I will migrate to this since this is developed by upstream and doesn't require a `Dockerfile` change. Closing this issue.
